In [13]:
import numpy as np
import scipy


array =  np.array([[1,2,3,4,5],[1,2,3,4,5]])
print (arrayld)

[[1 2 3 4 5]
 [1 2 3 4 5]]


In [14]:
print (type(array))

<class 'numpy.ndarray'>


In [15]:
# array dim
print(array.shape)

(2, 5)


In [18]:
# specific array 
print (array[1,2])
print (array[1,:5])

3
[1 2 3 4 5]


In [19]:
array < 3

array([[ True,  True, False, False, False],
       [ True,  True, False, False, False]], dtype=bool)

In [20]:
array2 = array + array

In [21]:
array2

array([[ 2,  4,  6,  8, 10],
       [ 2,  4,  6,  8, 10]])